In [2]:
import torch

# Tensor : Scalar

In [4]:
scalar = torch.tensor([3.])
print(scalar)

tensor([3.])


# Tensor : Vector

In [5]:
vector = torch.tensor([1., 2., 3.])
print(vector)

tensor([1., 2., 3.])


In [10]:
vector1 = torch.tensor([2., 3., 4.])
vector2 = torch.tensor([5., 6., 7.])

add = vector1 + vector2
add2 = torch.add(vector1, vector2)
dot = torch.dot(vector1, vector2)

print('add : ', add)
print('add2 :', add2)
print('dot : ', dot)

add :  tensor([ 7.,  9., 11.])
add2 : tensor([ 7.,  9., 11.])
dot :  tensor(56.)


# Tensor : Martix

In [17]:
matrix = torch.tensor([[1., 2.], [3., 4.]])
print(matrix)

tensor([[1., 2.],
        [3., 4.]])


In [14]:
matrix1 = torch.tensor([[1., 2.], [3., 4.]])
matrix2 = torch.tensor([[5., 6.], [7., 8.]])

sum_mat = matrix1 + matrix2
print('sum : ', sum_mat)

mul_mat = matrix1 * matrix2
print('mul : ', mul_mat)

matmul = torch.matmul(matrix1, matrix2)
print('matmul : ', matmul)

sum :  tensor([[ 6.,  8.],
        [10., 12.]])
mul :  tensor([[ 5., 12.],
        [21., 32.]])
matmul :  tensor([[19., 22.],
        [43., 50.]])


# Tensor : Tensor (2차원 matrix) 

In [18]:
tensor = torch.tensor([[[1., 2.], [3., 4.]], [[5., 6.], [7., 8.]]])
print(tensor)

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


In [22]:
# 2x2x2 tensor
tensor1 = torch.tensor([[[1., 2.], [3., 4.]], [[5., 6.], [7., 8.]]])
tensor2 = torch.tensor([[[9., 10.], [11., 12.]], [[13., 14.], [15., 16.]]])

mul_tensor = torch.mul(tensor1, tensor2)
print('mul : ', mul_tensor)

matmul_tensor = torch.matmul(tensor1, tensor2)
print('matmul : ', matmul_tensor)
print('matmul shape : ', matmul_tensor.shape)
# matmul process :
# [[(1*9)+(2*11)],[(1*10)+(2*12)], [(5*13)+(6*15)], [(5*14)+(6*16)], [(3*9)+(4*11)], [(3*19)+(4*12)], [(5*13)+(6*15)]]

mul :  tensor([[[  9.,  20.],
         [ 33.,  48.]],

        [[ 65.,  84.],
         [105., 128.]]])
matmul :  tensor([[[ 31.,  34.],
         [ 71.,  78.]],

        [[155., 166.],
         [211., 226.]]])
matmul shape :  torch.Size([2, 2, 2])


# Autograd

In [2]:
import torch

# torch.cuda.is_available : torch module 이용할 때 GPU 이용할 수 있는지 파악
if torch.cuda.is_available() :
    DEVICE = torch.device('cuda')
else:
    DEVICE = torch.device('cpu')

In [3]:
BATCH_SIZE = 64
INPUT_SIZE = 1000
HIDDEN_SIZE = 100
OUTPUT_SIZE = 10

In [35]:
x = torch.randn(BATCH_SIZE, 
                INPUT_SIZE, 
                device = DEVICE, 
                dtype = torch.float, 
                requires_grad = False)
y = torch.randn(BATCH_SIZE, 
                OUTPUT_SIZE, 
                device = DEVICE, 
                dtype = torch.float, 
                requires_grad = False)
w1 = torch.randn(INPUT_SIZE, 
                HIDDEN_SIZE, 
                device = DEVICE, 
                dtype = torch.float, 
                requires_grad = True)
w2 = torch.randn(HIDDEN_SIZE, 
                OUTPUT_SIZE, 
                device = DEVICE, 
                dtype = torch.float, 
                requires_grad = True)

In [36]:
learning_rate = 1e-6
for t in range (1, 501) :
    # clamp 라는 비선형함수 추가해서 예측값 구하기 / 여기서는 min = 0 이라 ReLU 랑 같음
    y_pred = x.mm(w1).clamp(min = 0).mm(w2)
    
    loss = (y_pred - y).pow(2).sum()
    if t % 100 == 0 :
        print("Iteration : ", t, "\t", "Loss : ", loss.item())
    loss.backward()
    
    # 해당 시점의 Gradient 값을 고정해놓고 parameters 값 업데이트
    with torch.no_grad() :
        w1 -= learning_rate * w1.grad
        w2 -= learning_rate * w2.grad
        
        # 업데이트가 끝났다면 이제 새로 Gradient를 계산할 수 있게 0으로 초기화
        w1.grad.zero_() 
        w2.grad.zero_()

Iteration :  100 	 Loss :  959.4061279296875
Iteration :  200 	 Loss :  14.716306686401367
Iteration :  300 	 Loss :  9.17580795288086
Iteration :  400 	 Loss :  9.502907752990723
Iteration :  500 	 Loss :  5.264459609985352
